#!/usr/bin/with-contenv bash

# Determine if setup is needed
if ! command -v ssh; then
  ## Ubuntu
  if [ -f /usr/bin/apt ]; then
    apt-get update
    apt-get install --no-install-recommends -y \
      ssh
  fi
  # Alpine
  if [ -f /sbin/apk ]; then
    apk add --no-cache \
      ssh
  fi
fi
